### ISSUE TITLE
Ownership constraints

### ISSUE THREAD

**Issue by TobiasWrigstad** [fxpl/frankenscript#12]
# Region isolation

* Inter-region references lead to freezing #50
* Intra-region references permitted :heavy_check_mark: 
* Reference from region object to objects owned by its region permitted :heavy_check_mark: 
* Reference to region object permitted :heavy_check_mark: 

# External uniqueness

* Only one incoming reference to a region object from outside of the region :heavy_check_mark: 

# Borrowing

* We permit references from the stack into open regions :heavy_check_mark:

**Comment by xFrednet** [comment]
I believe all of these have been implemented. I'll close the issue for now
