### ISSUE TITLE
Misc Cosmetics

### ISSUE THREAD

**Issue by TobiasWrigstad** [fxpl/frankenscript#36]
1. [x] The immutable region should have another colour, maybe something greenish
2. [x] We should colour references to immutable objects in a special colour and references that break encapsulation red
3. [ ] Maybe we should prune the output in the command line? I feel too much is printed so the signal to noise ratio is low.
4. [x] Better error messages
5. [x] It seems we sometimes use `foo x` and sometimes `foo(x)`. We should be consistent! IMO: only `move` should be an operator, the rest functions. 
6. [x] Split object count into local and global objects
7. [x] Mark global objects (Maybe by coloring their rc or have a (global) after it)

**Comment by xFrednet** [comment]
Closing this issue, I've created #54 for the last open item
